### ISSUE TITLE
External controller vs. Modal GUI interface

### ISSUE THREAD

**Issue by mungewell** [TheKikGen/MPC-LiveXplore-bootstrap#4]
Can you confirm the operation with the external controller modules (`anyctrl` and `anyctrl-lt`)?

Are you confined to using functions current shown in the GUI/Screen, or can you access functions which aren't showing (ie track/pad mutes regardless of screen mode)?

Bonus question - if you are crazy enough to loop a cable from Midi out -> Midi in, can the MPC sequence itself? _Maybe this is a way to 'improve' the looper in a live performance._

**Comment by TheKikGen** [comment]
In fact, you could build a kind of "macro" utility, because all buttons are managed with midi (on the "Private" port), and you can record that in a midi track !  For that, it is possible to expose the Private port to the "public" visible ports (as I do).

Concerning hidden functions : you have 128 buttons possibility.  I didn't test all.
Some functions are directly mapped, others need Shift...or a specific mode.
It is possible to simulate a button press/relese , even if you don't have the real button on your Mpc.
e.g. Pad Mixer, mutes, solo, track edit, etc...

e.g. : when simulating a Force on my Mpc Live, i use the shift + pad combination to launch a row.
So possibilities are huge.

https://github.com/TheKikGen/MPC-LiveXplore/blob/master/src/preload_libs/tkgl_mpcmapper.c
